services:
  proxy:
    image: ghcr.io/brandon-otoole/are-you-the-spy-proxy
    build: ./proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "8000:80"

  frontend:
    image: ghcr.io/brandon-otoole/are-you-the-spy-frontend
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "8080:8080"

  backend:
    image: ghcr.io/brandon-otoole/are-you-the-spy-backend
    build:
      context: ./backend
      target: development
    volumes:
      - ./backend/src:/app/src
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
