version: '3.8'
services:
  frontend:
    environment:
      - DEBUG_PLACEHOLDER=DEBUG_TRUE
      - HTTP_URL=http://localhost:8080
      - SOCKET_URL=ws://localhost:8080

    depends_on:
      - backend
    build: frontend/
    ports:
      - "8080:80"
  backend:
    environment:
      - PORT=3000

    build: backend/
